StoreApp.UI/Pages/Cart.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.VisualBasic;
using StoreApp.Business.Abstract;
using StoreApp.DataAccess.UnitOfWork;
using StoreApp.Entities.Entity;

namespace StoreApp.UI.Pages;


public class CartModel : PageModel
{
    public Cart Cart { get; set; }
    public string ReturnUrl { get; set; } = "/";

    private readonly IProductService _productService;
    private readonly IMapper _mapper;


    public CartModel(IProductService productService, IMapper mapper, Cart cart)
    {
        _productService = productService;
        _mapper = mapper;
        Cart = cart;
    }

    public void OnGet(string returnUrl)
    {
        ReturnUrl = returnUrl ?? "/";
    }

    public async Task<IActionResult> OnPost(string id,string returnUrl)
    {
        var result = await _productService.GetByIdAsync(id,false);
        var addCartItem= _mapper.Map<Product>(result.Data);
        if(result.IsSuccess)
        {
            Cart?.AddItem(addCartItem,1);
        }
        return Page();
    }

    public async Task<IActionResult> OnPostRemove(string id,string returnUrl)
    {
        var result = await _productService.GetByIdAsync(id,false);
        var removeCartItem = _mapper.Map<Product>(result.Data);
        if(result.IsSuccess)
        {
            Cart?.RemoveCartItemLine(Cart.CartItems.First(cl => cl.Product.Id == id).Product);
        }
        return Page();
    }
}

StoreApp.UI/Pages/Cart.cshtml
@page "/Cart"
@using StoreApp.Entities.Entity
@model CartModel

<div>
    <div class="text-center display-6">
        Cart
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Ürün</th>
                <th>Miktar</th>
                <th>Fiyat</th>
                <th>Toplam Fiyat</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model.Cart?.CartItems ?? Enumerable.Empty<CartItem>())
                {
                    <tr>
                        <td>@item.Product.Name</td>
                        <td>@item.Quantity</td>
                        <td>@item.Product.Price.ToString("c")</td>
                        <td>@((item.Product.Price * item.Quantity).ToString("c2"))</td>
                        <td>
                            <form method="post" asp-page-handler="Remove">
                                <input type="hidden" name="id" value="@item.Product.Id">
                                <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                                <button type="submit" class="btn btn-danger">
                                    Sil
                                </button>
                            </form>
                        </td>
                    </tr>
                }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Toplam Fiyat:</td>
                <td class="text-right text-danger">
                    @Model.Cart?.GetTotalPrice().ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>
</div>   

StoreApp.UI/Pages/Contact.cshtml
@page "/ContactUs"


 <div class="contact-info">
        <div>
            <i class="fa-solid fa-phone"></i>
            <p>+1 (555) 123-4567</p>
        </div>
        <div>
            <i class="fa-solid fa-mailbox"></i>
            <p>info@example.com</p>
        </div>
        <div>
            <i class="fas fa-map-marker-alt"></i>
            <p>123 Street Name, City, Country</p>
        </div>
    </div>